name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Builds on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name:
          - linux-x64-musl
          - macos-x64
          - macos-aarch64

        include:
          - name: linux-x64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exe: wait-on

          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin
            exe: wait-on

          - name: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            exe: wait-on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build for Release
        run: cargo build --release --target ${{ matrix.target }}
